sudo: required
services:
    - docker

before_install:
    - docker build -t rajathongal/docker-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true rajathongal/docker-react-app npm run test -- --coverage

deploy:
    /*it is a secret*/ 